name: "Setup kam"
description: "Install Rust Cargo environment and the latest version of kam with version-aware caching"
# Branding labels (activity icon + purple color) - v1.1 update
branding:
  icon: "activity"
  color: "purple"
inputs:
  github-token:
    description: "GitHub Token for cache and rate limit enhancement"
    required: false
    default: ${{ github.token }}
  enable-cache:
    description: "Toggle to enable caching of kam artifacts (true/false). Default: 'true'"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Install Rust (with Cargo)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Fetch latest kam version (for cache key)
      id: get-kam-version
      shell: bash
      run: |
        set -eu
        # Use python to parse JSON for cross-platform reliability
        JSON=$(curl -s https://crates.io/api/v1/crates/kam)
        LATEST_VERSION=$(printf "%s" "$JSON" | python - <<'PY'
import json,sys
print(json.load(sys.stdin)['crate']['max_version'])
PY
)
        echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
        echo "Fetched latest kam version: $LATEST_VERSION"

    - name: Cache kam (version-specific)
      if: ${{ inputs.enable-cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/bin/kam
        key: ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}
        restore-keys: |
          ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-

    - name: Cache kam (Windows)
      if: ${{ inputs.enable-cache == 'true' && runner.os == 'Windows' }}
      uses: actions/cache@v4
      with:
        path: |
          %USERPROFILE%/.cargo/registry/cache
          %USERPROFILE%/.cargo/git/db
          %USERPROFILE%/.cargo/bin/kam.exe
        key: ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}
        restore-keys: |
          ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-

    - name: Install latest kam (if not cached)
      shell: bash
      run: |
        if command -v kam &> /dev/null; then
          INSTALLED_VERSION=$(kam --version | awk '{print $2}')
          if [ "$INSTALLED_VERSION" = "${{ steps.get-kam-version.outputs.latest_version }}" ]; then
            echo "kam $INSTALLED_VERSION already installed (matches latest) - skipping installation"
            exit 0
          fi
          echo "Installed kam version $INSTALLED_VERSION is outdated - reinstalling latest"
        fi
        cargo install --force kam
        kam --version
