name: "Setup kam"
description: "Install Rust Cargo environment and the latest version of kam with version-aware caching"

branding:
  icon: "activity"
  color: "purple"
inputs:
  github-token:
    description: "GitHub Token for cache and rate limit enhancement"
    required: false
    default: ${{ github.token }}
  enable-cache:
    description: "Toggle to enable caching of kam artifacts (true/false). Default: 'true'"
    required: false
    default: "true"
  template-url:
    description: "Optional URL to download and import via 'kam tmpl import'"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Rust (with Cargo)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Fetch latest kam version (for cache key)
      id: get-kam-version
      shell: bash
      run: |
        set -eu
        USER_AGENT="setup-kam-action/1.0 (github.com/MemDeco-WG/setup-kam)"
        # Prefer crates.io as the primary source for versions; fallback to GitHub releases.
        URL="https://crates.io/api/v1/crates/kam"
        TMP_FILE_CRATES=$(mktemp)
        STATUS=$(curl -sS -w "%{http_code}" -H "User-Agent: $USER_AGENT" -H "Accept: application/json" --retry 3 --retry-delay 2 --max-time 15 -o "$TMP_FILE_CRATES" "$URL" 2>/dev/null || echo "000")
        CRATES_JSON=$(cat "$TMP_FILE_CRATES" || true)
        rm -f "$TMP_FILE_CRATES" || true
        if [ "$STATUS" = "200" ] && [ -n "$CRATES_JSON" ]; then
          PYTHON_BIN=$(command -v python || command -v python3 || true)
          if [ -n "$PYTHON_BIN" ]; then
            LATEST_VERSION=$(echo "$CRATES_JSON" | $PYTHON_BIN -c 'import json,sys; d=json.load(sys.stdin); print(d.get("crate",{}).get("max_version",""))' || true)
          else
            LATEST_VERSION=$(echo "$CRATES_JSON" | sed -n 's/.*"max_version":[[:space:]]*"\([^"]\+\)".*/\1/p' || true)
          fi
          LATEST_VERSION=$(echo "$LATEST_VERSION" | sed -E 's/^[vV]//' | tr -d '\r\n') || true
        else
          echo "crates.io lookup returned HTTP $STATUS; response preview:" >&2
          echo "$CRATES_JSON" | sed -n '1,10p' >&2 || true
          # Fallback to GitHub releases
          GH_TOKEN="${{ inputs.github-token }}"
          GH_API="https://api.github.com/repos/MemDeco-WG/Kam/releases/latest"
          TMP_FILE_GH=$(mktemp)
          if [ -n "$GH_TOKEN" ]; then
            GH_STATUS=$(curl -sS -w "%{http_code}" -H "User-Agent: $USER_AGENT" -H "Authorization: token $GH_TOKEN" --retry 3 --retry-delay 2 --max-time 15 -o "$TMP_FILE_GH" "$GH_API" 2>/dev/null || echo "000")
          else
            GH_STATUS=$(curl -sS -w "%{http_code}" -H "User-Agent: $USER_AGENT" --retry 3 --retry-delay 2 --max-time 15 -o "$TMP_FILE_GH" "$GH_API" 2>/dev/null || echo "000")
          fi
          GH_JSON=$(cat "$TMP_FILE_GH" || true)
          rm -f "$TMP_FILE_GH" || true
          if [ "$GH_STATUS" = "200" ] && [ -n "$GH_JSON" ]; then
            PYTHON_BIN=$(command -v python || command -v python3 || true)
            if [ -n "$PYTHON_BIN" ]; then
              TAG=$(echo "$GH_JSON" | $PYTHON_BIN -c 'import json,sys; d=json.load(sys.stdin); print(d.get("tag_name",""))' || true)
            else
              TAG=$(echo "$GH_JSON" | sed -n 's/.*"tag_name":[[:space:]]*"\([^"]\+\)".*/\1/p' || true)
            fi
            LATEST_VERSION=$(echo "$TAG" | sed -E 's/^[vV]//' | tr -d '\r\n') || true
          else
            echo "GitHub releases lookup failed with HTTP $GH_STATUS; response preview:" >&2
            echo "$GH_JSON" | sed -n '1,10p' >&2 || true
            LATEST_VERSION="unknown"
          fi
        fi

        echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
        echo "Fetched latest kam version: $LATEST_VERSION"

    - name: Cache kam (Linux/macOS)
      if: ${{ inputs.enable-cache == 'true' && runner.os != 'Windows' }}
      uses: actions/cache@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        path: |
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/bin/kam
        key: ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-

    - name: Cache kam (Windows)
      if: ${{ inputs.enable-cache == 'true' && runner.os == 'Windows' }}
      uses: actions/cache@v4.3.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        path: |
          %USERPROFILE%/.cargo/registry/cache
          %USERPROFILE%/.cargo/git/db
          %USERPROFILE%/.cargo/bin/kam.exe
        key: ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-

    - name: Check installed kam version and decide whether to install
      id: check-kam
      shell: bash
      run: |
        set -eu
        LATEST_VERSION="${{ steps.get-kam-version.outputs.latest_version }}"
        LATEST_VERSION=$(echo "$LATEST_VERSION" | sed -E 's/^[vV]//' | tr -d '\r\n')

        INSTALLED_VERSION=""
        if command -v kam &> /dev/null; then
          INSTALLED_VERSION=$(kam --version 2>/dev/null | awk '{print $2}' | sed -E 's/^[vV]//' | tr -d '\r\n') || true
        fi
        echo "installed_version=$INSTALLED_VERSION" >> $GITHUB_OUTPUT

        if [ -z "$LATEST_VERSION" ] || [ "$LATEST_VERSION" = "unknown" ]; then
          # If we don't know the target version, only install if nothing is installed.
          if [ -z "$INSTALLED_VERSION" ]; then
            echo "should_install=true" >> $GITHUB_OUTPUT
          else
            echo "should_install=false" >> $GITHUB_OUTPUT
          fi
        else
          # If we have a target version, install if installed version does not match.
          if [ "$INSTALLED_VERSION" = "$LATEST_VERSION" ]; then
            echo "should_install=false" >> $GITHUB_OUTPUT
          else
            echo "should_install=true" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Install latest kam (explicit version via actions-rs/cargo)
      if: ${{ steps.check-kam.outputs.should_install == 'true' && steps.get-kam-version.outputs.latest_version != 'unknown' }}
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force --version ${{ steps.get-kam-version.outputs.latest_version }} kam

    - name: Install latest kam (no explicit version via actions-rs/cargo)
      if: ${{ steps.check-kam.outputs.should_install == 'true' && steps.get-kam-version.outputs.latest_version == 'unknown' }}
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force kam

    - name: Download and import template (Linux/macOS)
      if: ${{ inputs.template-url != '' && runner.os != 'Windows' }}
      shell: bash
      run: |
        set -eu
        USER_AGENT="setup-kam-action/1.0 (github.com/MemDeco-WG/setup-kam)"
        echo "Downloading template from ${{ inputs.template-url }}"
        TMPDIR=$(mktemp -d)
        # Preserve the filename/extension from the URL and strip query string so kam can detect archive format (zip / tar.gz)
        url="${{ inputs.template-url }}"
        filename=$(basename "$url")
        # Strip common query params and fragments (e.g., ?raw=true or #fragment) that can follow the file name
        filename=$(echo "$filename" | sed -E 's/[?&#].*$//')
        # Validate filename uses a recognized archive extension
        if ! [[ "$filename" =~ \.(zip|tar\.gz|tar\.bz2|tgz|tar)$ ]]; then
          echo "Error: The template URL does not contain a recognized archive extension (expected .zip, .tgz, .tar.gz, .tar.bz2, or .tar)."
          echo "Downloaded filename: $filename"
          echo "Please provide a URL that includes the filename and a recognized archive extension, or provide an already-extracted template directory."
          exit 1
        fi
        TMP_FILE=$(mktemp)
        STATUS=$(curl -sSL -w "%{http_code}" -H "User-Agent: $USER_AGENT" --retry 3 --retry-delay 2 --retry-connrefused --max-time 60 -o "$TMPDIR/$filename" "$url" 2>/dev/null || echo "000")
        if [ "$STATUS" != "200" ]; then
          echo "Template download returned HTTP $STATUS; response preview (first 1K):" >&2
          head -c 1024 "$TMPDIR/$filename" | sed -n '1,20p' >&2 || true
          exit 1
        fi
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "Importing template using kam..."
        kam tmpl import "$TMPDIR/$filename"

    - name: Download and import template (Windows)
      if: ${{ inputs.template-url != '' && runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $UserAgent = 'setup-kam-action/1.0 (github.com/MemDeco-WG/setup-kam)'
        Write-Host "Downloading template from ${{ inputs.template-url }}"
        $url = "${{ inputs.template-url }}"
        $tmp = Join-Path $env:TEMP 'kam-tmpl'
        New-Item -ItemType Directory -Force -Path $tmp | Out-Null
        # Extract path from URL and resolve the filename (strip query string and fragment)
        $file = [System.IO.Path]::GetFileName([System.Uri]::new($url).AbsolutePath)
        # Validate filename uses a recognized archive extension
        if (-not ($file -match '\.(zip|tar\.gz|tar\.bz2|tgz|tar)$')) {
          Write-Error "Error: The template URL does not contain a recognized archive extension (expected .zip, .tgz, .tar.gz, .tar.bz2, or .tar)."
          Write-Error "Downloaded filename: $file"
          Write-Error "Please provide a URL that includes the filename and a recognized archive extension, or provide an already-extracted template directory."
          exit 1
        }
        $dest = Join-Path $tmp $file
        Invoke-WebRequest -UseBasicParsing -UserAgent $UserAgent -Uri $url -OutFile $dest
        $env:Path = (Join-Path $env:USERPROFILE '.cargo\\bin') + ';' + $env:Path
        Write-Host "Importing template using kam..."
        kam tmpl import $dest
