name: "Setup kam"
description: "Install Rust Cargo environment and the latest version of kam with version-aware caching"
# Branding labels (activity icon + purple color) - v1.1 update
# NOTE: 'latest' tag has been updated to point to 'main'
branding:
  icon: "activity"
  color: "purple"
inputs:
  github-token:
    description: "GitHub Token for cache and rate limit enhancement"
    required: false
    default: ${{ github.token }}
  enable-cache:
    description: "Toggle to enable caching of kam artifacts (true/false). Default: 'true'"
    required: false
    default: "true"
  template-url:
    description: "Optional URL to download and import via 'kam tmpl import'"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Rust (with Cargo)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Fetch latest kam version (for cache key)
      id: get-kam-version
      shell: bash
      run: |
        set -eu
        # Use python one-liner to parse JSON (avoids heredoc indentation issues)
        LATEST_VERSION=$(curl -s https://crates.io/api/v1/crates/kam | python -c "import json,sys; print(json.load(sys.stdin)['crate']['max_version'])")
        echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
        echo "Fetched latest kam version: $LATEST_VERSION"

    - name: Cache kam (Linux/macOS)
      if: ${{ inputs.enable-cache == 'true' && runner.os != 'Windows' }}
      uses: actions/cache@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        path: |
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/bin/kam
        key: ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-

    - name: Cache kam (Windows)
      if: ${{ inputs.enable-cache == 'true' && runner.os == 'Windows' }}
      uses: actions/cache@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        path: |
          %USERPROFILE%/.cargo/registry/cache
          %USERPROFILE%/.cargo/git/db
          %USERPROFILE%/.cargo/bin/kam.exe
        key: ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-kam-${{ steps.get-kam-version.outputs.latest_version }}-

    - name: Install latest kam (if not cached)
      shell: bash
      run: |
        if command -v kam &> /dev/null; then
          INSTALLED_VERSION=$(kam --version | awk '{print $2}')
          if [ "$INSTALLED_VERSION" = "${{ steps.get-kam-version.outputs.latest_version }}" ]; then
            echo "kam $INSTALLED_VERSION already installed (matches latest) - skipping installation"
            exit 0
          fi
          echo "Installed kam version $INSTALLED_VERSION is outdated - reinstalling latest"
        fi
        cargo install --force kam
        kam --version

    - name: Download and import template (Linux/macOS)
      if: ${{ inputs.template-url != '' && runner.os != 'Windows' }}
      shell: bash
      run: |
        set -eu
        echo "Downloading template from ${{ inputs.template-url }}"
        TMPDIR=$(mktemp -d)
        curl -fsSL -o "$TMPDIR/tmpl" "${{ inputs.template-url }}"
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "Importing template using kam..."
        kam tmpl import "$TMPDIR/tmpl"

    - name: Download and import template (Windows)
      if: ${{ inputs.template-url != '' && runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Write-Host "Downloading template from ${{ inputs.template-url }}"
        $tmp = Join-Path $env:TEMP 'kam-tmpl'
        New-Item -ItemType Directory -Force -Path $tmp | Out-Null
        $dest = Join-Path $tmp 'tmpl'
        Invoke-WebRequest -UseBasicParsing -Uri "${{ inputs.template-url }}" -OutFile $dest
        $env:Path = (Join-Path $env:USERPROFILE '.cargo\\bin') + ';' + $env:Path
        Write-Host "Importing template using kam..."
        kam tmpl import $dest
